//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate Fail.
        /// </summary>
        internal static string Authenticate_Fail {
            get {
                return ResourceManager.GetString("Authenticate Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthenticateSuccess.
        /// </summary>
        internal static string Authenticate_Success {
            get {
                return ResourceManager.GetString("Authenticate Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteFail.
        /// </summary>
        internal static string Delete_Fail {
            get {
                return ResourceManager.GetString("Delete Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteSuccess.
        /// </summary>
        internal static string Delete_Success {
            get {
                return ResourceManager.GetString("Delete Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllFail.
        /// </summary>
        internal static string Get_All_Fail {
            get {
                return ResourceManager.GetString("Get All Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllSuccess.
        /// </summary>
        internal static string Get_All_Success {
            get {
                return ResourceManager.GetString("Get All Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFail.
        /// </summary>
        internal static string Get_Fail {
            get {
                return ResourceManager.GetString("Get Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSuccess.
        /// </summary>
        internal static string Get_Success {
            get {
                return ResourceManager.GetString("Get Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertFail.
        /// </summary>
        internal static string Insert_Fail {
            get {
                return ResourceManager.GetString("Insert Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertSuccess.
        /// </summary>
        internal static string Insert_Success {
            get {
                return ResourceManager.GetString("Insert Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterFail.
        /// </summary>
        internal static string Register_Fail {
            get {
                return ResourceManager.GetString("Register Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Success.
        /// </summary>
        internal static string Register_Success {
            get {
                return ResourceManager.GetString("Register Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateFail.
        /// </summary>
        internal static string Update_Fail {
            get {
                return ResourceManager.GetString("Update Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateSuccess.
        /// </summary>
        internal static string Update_Success {
            get {
                return ResourceManager.GetString("Update Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserExist.
        /// </summary>
        internal static string User_Existed {
            get {
                return ResourceManager.GetString("User Existed", resourceCulture);
            }
        }
    }
}
